# (for testing github workflow timing
name: Slack Notify Test

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # runs every 15 minutes on Saturday
    - cron:  '0 0,6,12,18 * * *'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      uses: edge/simple-slack-notify@master
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      with:
        channel: '#jbum-testing'
        text: "Testing github slack messaging"
        color: 'good'
        username: jbumbot
        fields: |
          [{ "title": "Time triggered", "value": "${(new Date(Date.now())).toLocaleDateString()} ${(new Date(Date.now())).toLocaleTimeString()}", "short": true }]      
