name: SVG pregeneration
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '10 19 * * *'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git pull
          npm install
          npm run sparklines
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add img/generated/sparklines/*
          git commit -m "generated sparklines"
          git push origin master
      - uses: StateOfCalifornia/azblob-upload-artifact@master     
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container: '$web'
          name: .
          path: path/to/artifact
          cleanup: false
          sync: false
          