name: SVG pregeneration test
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run once an hour
    - cron:  '0/15 * * * *'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Los_Angeles"

      - uses: actions/checkout@v2
      - run: |
          # git pull origin main
          npm install
          npm run svgPregen
